### ISSUE TITLE
Man page retrieval on Ubuntu 11.10

### ISSUE THREAD

**Issue by Pankrat** [jimenezrick/vimerl#12]
The `erlang-manpages` package on Ubuntu 11.10 installs the Erlang man pages with filenames like that:

`/usr/share/man/man3/gen_server.3erl.gz`

However, the globbing in `erlang_complete.vim` is too restrictive to pick that up (the _erl_ suffix of the extension). Replacing the `?` with the `*` wildcard fixes the problem:

```
@@ -132,7 +132,7 @@
            let function_name = matchstr(element, a:base . '\w*')
            let number_of_args = matchstr(element, '\d\+', len(function_name))
            let number_of_comma = max([number_of_args - 1, 0])
-           let file_path = g:erlang_man_path . '/man?/' . a:module . '.?' . g:erlang_man_extension
+           let file_path = g:erlang_man_path . '/man?/' . a:module . '.*' . g:erlang_man_extension
            let description = ''

            " Don't look man pages if the module is present in the current directory
```

Cheers, Ludwig

**Comment by jimenezrick** [comment]
In the plugin doc (`:help vimerl`) there is explained an option to set the extension of your man pages (`:help erlang_man_extension`).

The quick fix should be to put in your `.vimrc` something like this:

```
let erlang_man_extension = "erl.gz"
```

And also:

```
let erlang_completion_grep = "zgrep"
```

But I think this option is crap, a more generic wildcard (like the one you suggest) which handles all kind of extensions should be used. I'am going to change that.

**Comment by jimenezrick** [comment]
These two commits should close this issue:

c55dce2cbde9b07bb10aac6d5f00556045535699
7f273dbe5b42e383f5ea65cc7d7cf432b4266a9a

Please test and if the issue persist, reopen.

Also I'm going to try to remove the `erlang_man_path` option.
