### ISSUE TITLE
Indentation is incorrect in begin/end blocks.

### ISSUE THREAD

**Issue by whitelynx** [jimenezrick/vimerl#23]
This seems to have broken since the addition of erlang_indent.erl. Here's examples of typing the same function body in 56219e8 and 458da49:

``` erlang
% In 56219e8:
correct_indentation_on_begin_end() ->
    Foo = begin
            example_func(),
            another_example_func()
    end,
    lists:reverse(Foo).

% In 458da49:
broken_indentation_on_begin_end() ->
    Foo = begin
        example_func(),
    another_example_func()
    end,
lists:reverse(Foo).
```

**Comment by whitelynx** [comment]
Just put together a shorter example of the breakage:

``` erlang
bleh() ->
    Foo = begin
        blargh()
        end,
lists:reverse(Foo).
```

**Comment by jimenezrick** [comment]
Ups! I forgot to handle `begin...end` expression... I'll fix it this week :-)

**Comment by whitelynx** [comment]
Cool, thanks! I found a few more inconsistencies in playing with it more:

``` erlang
% When '||' is not at the end of the line, the guard clauses get an extra level
% of indentation, but not when '||' is at the end.
list_comp() ->
    Foo = [something(Foo)
            || Foo <- Baz,
                Foo =/= undefined
                ],
    tl(Foo).
    Foo = [
            something(Foo) ||
            Foo <- Baz,
            Foo =/= undefined
            ],
    tl(Foo).
    Foo = [
            something(Foo) || Foo <- Baz,
                Foo =/= undefined
                ],
    tl(Foo).

% If there's a begin/end inside a list comprehension, it seems to break all
% indentation until the end of the function.
begin_end_in_list_comp() ->
    Foo = [begin
            Bar = something(Foo),
            Bar
            end
            || Foo <- Baz,
            Foo =/= undefined
            ],
            Fez = [
            arf,
            bark
            ],
            [hd(Fez) | tl(Foo)].
```

Should I open a separate issue for these?

**Comment by jimenezrick** [comment]
No, keep all this info in this issue.

**Comment by jimenezrick** [comment]
Patch for fixing `begin...end` ready.

**Comment by jimenezrick** [comment]
Off-topic question: Why do you use `=/=` comparing against an atom? Because I have seen it several times but I don't know the advantages... :-/

**Comment by jimenezrick** [comment]
About the list comprehensions, I can't reproduce your issue. Try with the new commit I am going to push that solves the `begin...end` matter and see if that also solves it.

Look in `test/` to see some cases of how Vimerl handle list comprehensions.

**Comment by whitelynx** [comment]
`/=` and `=/=` are related in the same way as `==` and `=:=`. If I remember correctly, `==` and `/=` just compare value, whereas `=:=` and `=/=` compare type as well... for instance, `10 == 10.0.` evaluates to `true`, while `10 =:= 10.0.` evaluates to `false`.

I pulled and installed the latest version, and now I'm not getting indentation at all. I've removed my clone of the repo, re-cloned, re-installed (I use Arch, so I'm installing using the PKGBUILD posted at https://gist.github.com/2228512), and double-checked my settings when editing an Erlang file (`nocindent    nosmartindent    indentexpr=ErlangIndent()    nopaste    filetype=erlang`) but when I try entering code, it won't indent at all; it won't even keep the same indent level when I'm continuing something that's already indented.

**Comment by jimenezrick** [comment]
OK, the problem is that new indenter in Vimerl uses a pair of named FIFOs to communicate with the escript, and this FIFOs are created where the plugin is installed. So you must install the plugin in your $HOME/.vim.

I did like this because most of the Vim plugins create the temporal files inside the plugin directory as the most of the times, the users install them in their $HOMEs.

If you want, take a look at my vimrc to see my settings for filetype erlang: https://github.com/jimenezrick/vimconfig/blob/master/vimrc

**Comment by whitelynx** [comment]
Ok, I can confirm that the indentation issues are corrected in the latest git; all of the examples above work correctly for me now. Thanks!

It'd be nice to support installing the plugin globally (for instance, my group has a test server that several of us use, and our server app is written in Erlang, so we all want to use the plugin on there) and I have a couple of ideas on how to approach that change, but that should probably be a new issue.

**Comment by jimenezrick** [comment]
A simple and effective solution should be to fallback to /tmp if the plugin directory is not writeable. This should work for everybody.

**Comment by jimenezrick** [comment]
I pushed another commit which allows the FIFOs to be located in `/tmp`, check it out and see if now Vimerl works when installed in `/usr/share`.
