### ISSUE TITLE
Troubleshooting ErlangEnableShowErrors

### ISSUE THREAD

**Issue by mootboy** [jimenezrick/vimerl#24]
When I -include_lib(x.hrl) and x.hrl is a pretty massive hrl file all warnings and errors disappear from the .erl file I'm writing. Is there a way to show what happens in the compile cycle so I can troubleshoot?

Thanks for the awesome branch by the way!

**Comment by jimenezrick** [comment]
Do you refer to `-include_lib` or `-include`?

Because `include_lib` is for headers inside application directories. Are you including some header of the Erlang OTP, or a header from one of your applications?

Does the size of the header affects the behavior of Vimerl?

**Comment by mootboy** [comment]
I'm referring to `include_lib`, changing it to an `include` does not do any difference. It's within an application, but not a standard OTP header.

It seems to be the size, smaller headers work fine, but it might also be something within the header I'm including I guess. Which is why I want to troubleshoot somehow :)

**Comment by jimenezrick** [comment]
Well, beter use `erlc` directly and see what errors it gives. Are you using rebar? Does the compiler finds your application (of the header)?

**Comment by mootboy** [comment]
`erlc` was the ticket! Now I at least have some output to look at. I suspect it is something related to the structure of our application. Will close this one for now and file a true bug-report if I find that it really is a bug.

Thanks again for the help and branch!
