### ISSUE TITLE
Escript failure to load erlang_indent.erl

### ISSUE THREAD

**Issue by staticcat** [jimenezrick/vimerl#28]
When following the loading of the vimerl into cygwin through pathogen I get an escript error saying that erlang_indent.erl wasn't able to be loaded. The location of the file exists. 

The contents of my ./vimrc file is as follows;

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on

autocmd BufEnter *.escript                         if &filetype == '' | setlocal filetype=erlang | endif

**Comment by jimenezrick** [comment]
`erlang_indent.erl` needs to be in the same location as `indent/erlang.vim`. This happens on line 20 in those second script:

```
let s:erlang_indent_file = expand('<sfile>:p:h') . '/erlang_indent.erl'
```

Try to hardcode the real route in that assignment such as:

```
let s:erlang_indent_file = 'C:\.......'
```

See if that helps to find more details about the issue.

**Comment by staticcat** [comment]
They appear to be in the same location. I will try your code and give you a
heads up if that works.

From memory though the error on loading a .erl file in vim is that escript
couldn't locate the indent file, but it gives the full path to where it
exisits (and the file is there).

Very weird... Will let you know.
On Jul 29, 2012 11:09 PM, "Ricardo Catalinas Jiménez" <
reply@reply.github.com>
wrote:

**Comment by jimenezrick** [comment]
By the way, I didn't perform any test on Windows platform because portability was not a priority for me. So, Cygwin should offer some compatibility aid but I don't expect Vimerl to work seamless.

Furthermore, I use FIFOs internally to communicate with the indenter and I don't know if such thing exists on Windows.
