### ISSUE TITLE
Not working on vim 7.3 under Mountain Lion

### ISSUE THREAD

**Issue by mkuznetsov** [jimenezrick/vimerl#39]
Copy tag to ~/.vim but nothing happened. On Lion I use this and all work without problems

**Comment by jimenezrick** [comment]
What do you mean by tag?

/Ricardo

**Comment by mkuznetsov** [comment]
This is autocorrection in change from "tar" to "tag". Instruction said - untar vimerl archive to ~/.vim start vim and work. I do it, but it is not working.

**Comment by jimenezrick** [comment]
Sorry, I don't have a Mac to test on this issue.

**Comment by aerosol** [comment]
It works on ML, I don't think it's mac-related.
@mkuznetsov Define "not working". `:scriptnames` perhaps?

**Comment by jimenezrick** [comment]
Feel free to reopen the issue if you find a bug and have more specific details.
