### ISSUE TITLE
vimerl reports incorrect compile-time errors 

### ISSUE THREAD

**Issue by tex** [jimenezrick/vimerl#48]
because it doesn't take in compilation rebar's deps path.

My modules includes files from deps, compilation with rebar works OK, but vimerl reports include errors.... 

The problem is made visible by this commit: 24babdcc4c792bbe422bfd8b18bfdfc28c91c141

Without this commit the incorrect errors are shown for a small moment, but then they are removed and only the real errors are visible.

**Comment by jimenezrick** [comment]
I can't find the 24babdc commit, can you check that?

**Comment by tex** [comment]
sorry, it is f81cdabbd5d12233e1fbd211f515ff2a17b95d95

**Comment by jimenezrick** [comment]
Take a look at #46 where there is an ongoing process of improving how the include paths are handled. After that fix, you should be able to get rid of that errors as the includes should work as expected.

By the way, are you using `-include_lib(...)`?

**Comment by tex** [comment]
I'm using -include_lib(...).

**Comment by tex** [comment]
I tried the #46, but I have two problems with it:
1. It works partially when a flat structure is used (only ./src)
   But it complains in every file that "unbounded variable File". But Rebar compiles it without warning.
   And indeed there is no unbounded variable.
2. Doesn't work if subdirectories are used (./src/elements, ./src/modules, ...)

**Comment by jimenezrick** [comment]
About 1, it should be fixed. I wrote it tonight so it's poorly tested :-/

**Comment by tex** [comment]
About 1, tested it and it works.

**Comment by jimenezrick** [comment]
And your errors from includes in Rebar deps?

**Comment by tex** [comment]
When the source code is in the ./src directory then it works.
But when the source is in ./src/elements/ then it cannot find the includes from Rebar deps.

**Comment by tex** [comment]
This patch "fixes" my problem. The interesting thing is that at the start all errors are shown (real erros and errors coming from wrong include paths) and then after a few hundrets of miliseconds the errors coming from wrong include paths are removed and only the real errors stay visible.

<pre>
diff --git a/compiler/erlang.vim b/compiler/erlang.vim
index da88b85..414ed20 100644
--- a/compiler/erlang.vim
+++ b/compiler/erlang.vim
@@ -48,6 +48,7 @@ function s:ShowErrors()
                execute "setlocal makeprg=" . s:erlang_check_file . "\\ \%"
        endif
        silent make!
+       call s:ClearErrors()
        for error in getqflist()
                let item         = {}
                let item["lnum"] = error.lnum
</pre>

**Comment by jimenezrick** [comment]
This patch fixes the problem completely?, or that thing you describe of errors disappearing after some milliseconds continues happening?

**Comment by tex** [comment]
Without this patch I see all errors. That is bad.
With this patch I see all errors for a few hundrets of miliseconds, then the errors coming from wrong include paths are removed and only the real errors are visible.

**Comment by cbertoldi** [comment]
Will this patch get included? It seem to fix the problem described by tex for me too.

**Comment by jimenezrick** [comment]
@cbertoldi: do you have the same symptoms and that patch fixes also them?

**Comment by cbertoldi** [comment]
Yes, I've applied the patch, and the error on the include_lib disappears
just after the blink of an eye.

On Tue, May 7, 2013 at 5:35 PM, Ricardo Catalinas Jiménez <
notifications@github.com> wrote:

> @cbertoldi https://github.com/cbertoldi: do you have the same symptoms
> and that patch fixes also them?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jimenezrick/vimerl/issues/48#issuecomment-17549828
> .

## 

È molto più bello sapere qualcosa di tutto, che sapere tutto di una cosa.

Blaise Pascal

**Comment by jimenezrick** [comment]
OK, I will apply it later.

**Comment by cbertoldi** [comment]
Thanks :)

**Comment by jimenezrick** [comment]
Done. It's not clear to me why this patch fixes this problem, so if you encounter again the same issue or have a better solution, just say it.
