### ISSUE TITLE
Word erased using omni complete

### ISSUE THREAD

**Issue by jimenezrick** [jimenezrick/vimerl#5]
Write some `Mod:Fun` which that when omni completed only has one suggestion:
1. Write `file:advise`.
2. Hit `Ctrl+x+o`, then `advise` will be erased and replaced by `(`. The `(` should be append to the tail.

**Comment by tapichu** [comment]
Bug fix - omni complete and only one suggestion

Omni complete deleted the function name when there was only one
suggestion.

Closed by ede8ef2c37f03e5b94f8db63d48407a1e723caf9.
