### ISSUE TITLE
Provide installation instructions for vim/pathogen novices

### ISSUE THREAD

**Issue by AlexCzar** [jimenezrick/vimerl#51]
README says that the plugin is compatible with pathogen, but doesn't specify how to install with it. This is confusing for novices. Should we `git clone` whole repository or just the `plugin` subdirectory?

**Comment by jimenezrick** [comment]
Any pathogen tutorial should explain the common case. But answering your question, just clone the entire repository in your `.vim/budle` directory. That's what I do for all my Vim plugins.
