### ISSUE TITLE
Error with gVim on Windows

### ISSUE THREAD

**Issue by carlosedp** [jimenezrick/vimerl#52]
I would like to know if the plugin is compatible with gVim on Windows.

When I try to load an .erl file, I got an error (tracked to the ftplugin/erlang.vim) in the line where there is a call to system('which erl').

Thanks

**Comment by jimenezrick** [comment]
No, sorry. Windows it's not supported. The plugin uses UNIX specific functionality.

**Comment by filmor** [comment]
Would you mind keeping this issue open and adding a note in the readme file?

**Comment by jimenezrick** [comment]
Tip for Windows users, now Vim 7.4 ships an Erlang indent script written in vimscript, I recommend you to take a look at it. I will make Vimerl use that indent script soon. For this error related to the `which` call, just remove that line and the next one.
