### ISSUE TITLE
 syntax checking does not work in macros

### ISSUE THREAD

**Issue by dcy** [jimenezrick/vimerl#53]
Hi! Vimerl is my favorite plugin, thanks.
I found that syntax checking does not work in macros.
![Uploading vimerl.png . . .]()

**Comment by dcy** [comment]
The variable in macro, Syntax checking will warning the variable is unuse.
The pictrue i can not upload success, It always "Something went really wrong and we can't process that image."

**Comment by jimenezrick** [comment]
Just paste an small example of code that triggers the issue.

**Comment by dcy** [comment]
![vimerl_assert](https://f.cloud.github.com/assets/1137238/1015069/da3fa652-0bcf-11e3-8cd6-870ba11fede0.png)
OK, The image works

**Comment by jimenezrick** [comment]
Vimerl does nothing special to check the syntax, it just calls the compiler on the current file. So, this is probably an issue with your code. Problaby, the ASSERT macro is disables and it isn't generating code, so the variable is effectively not used.

Try to compile your code without Vimerl to see if the errors also appears. Try to enable your ASSERT macro so that your variables are used.

**Comment by dcy** [comment]
I can compile my code with erl -make, and there is no warning

**Comment by jimenezrick** [comment]
And if you compile disabling the ASSERT?

**Comment by jimenezrick** [comment]
Look into your Emakefile to dissable the ASSERT,

**Comment by dcy** [comment]
The result is, of course,  
can't find include file "common.hrl"
 undefined macro 'ASSERT/2'

**Comment by jimenezrick** [comment]
In Vimerl?

**Comment by dcy** [comment]
Vimerl warning is unused

**Comment by jimenezrick** [comment]
So, the can't find include file "common.hrl" is using erl -make?

**Comment by jimenezrick** [comment]
Do you have something like and -ifdef for enabling the ASSERT?

**Comment by dcy** [comment]
Yes, I had, It works when i remove the "ifdef"

**Comment by jimenezrick** [comment]
The easiest way is to define in your header file the symbol that **enables the ASSERT**. So that Vimerl compiles the file with the ASSERT and the warning will disappear.

Add a -define(DEBUG, true) or whatever you need in your header.

I'm closing the issue as it is not a defect in Vimerl.

**Comment by dcy** [comment]
Ok, thanks
