### ISSUE TITLE
code formatter for vimerl

### ISSUE THREAD

**Issue by zhihuij** [jimenezrick/vimerl#57]
I really like writing erlang code with vimerl, but I need code formatting function to make all my code with same style, just like Ctrl+Shift+F with Eclipse for Java code.

I want to know whether there is any plan for this? or any ideas for how to implement this in vim?  thanks.

**Comment by jimenezrick** [comment]
If you mean the autoindent, it's already there, section 2.1 of the Vimerl's help explains it. If you mean a more sophisticated functionality of formatting all aspects of your code a la Eclipse, no. There is no intention of doing this and it would be high costly to do so.
