### ISSUE TITLE
Omni-completion with YCM

### ISSUE THREAD

**Issue by ojung** [jimenezrick/vimerl#63]
See @sedrik 's issue in the youcompleteme repo.

https://github.com/Valloric/YouCompleteMe/issues/862

Do you have an idea how to fix this?

**Comment by jimenezrick** [comment]
I checked vimerl's code and I cannot see the issue. Not really sure of what is happening.

**Comment by snowch** [comment]
@jimenezrick have you tried vimerl with https://github.com/Valloric/YouCompleteMe?  I couldn't get them working together either.
