### ISSUE TITLE
Unknown option: not env: encrypt: No such file or directory

### ISSUE THREAD

**Issue by alex-ethier** [jimenezrick/vimerl#64]
vim 7.3 clean install - osx 10.9.2 - vimerl:1.4.3

I'm getting this error with any erlang files
![vimerl](https://cloud.githubusercontent.com/assets/677604/3076088/1dc8c598-e3b1-11e3-8bab-a9ff6e66464b.jpg)

Any idea what is causing this?

Thanks!

**Comment by jimenezrick** [comment]
Sorry, no idea of what it could be. I don't have an OS X where to reproduce this.
