### ISSUE TITLE
parameterized modules are no longer support for ChicagoBoss

### ISSUE THREAD

**Issue by dcy** [jimenezrick/vimerl#65]
![2014-05-28-230353_948x258_scrot](https://cloud.githubusercontent.com/assets/1137238/3106116/5801e8f0-e679-11e3-84fe-3fab21f85249.png)

**Comment by jimenezrick** [comment]
I don't actually know if this experimental feature of Erlang was
deprecated. Maybe is that?

/Ricardo

**Comment by dcy** [comment]
I don't know too. But ChicagoBoss use parameterized modules and "./rebar compile" does not get any warning or error.

**Comment by choptastic** [comment]
Pmods were indeed removed in R16B, and ChicagoBoss uses a parse transform provided by the OTP team (https://github.com/erlang/pmod_transform) to support pmods.

I don't know what the fix would be to get vimerl to support them, though. I've just dealt with it when necessary.

**Comment by jimenezrick** [comment]
Maybe the parse transform needs to be specified at compile time and that's
why vimerl cannot check the code because I'm passing the standard flags to
the compiler.

/Ricardo

**Comment by choptastic** [comment]
Indeed, ChicagoBoss does a lot of odd things dynamically added during
compilation that are not explicitly specified in the code of a module.

Depending on how much of a pain it is, I may spend some time to figure out
how to get vimerl to work with CB, but for now, I'm not sure whta needs to
happen.

It's a hassle, but not something I'd say is a problem in vimerl - I suspect
there might be some configurations that can be done to get them to play
together nicely.

On Thu, May 29, 2014 at 2:03 AM, Ricardo Catalinas Jiménez <
notifications@github.com> wrote:

> Maybe the parse transform needs to be specified at compile time and that's
> why vimerl cannot check the code because I'm passing the standard flags to
> the compiler.
> 
> /Ricardo
> On May 29, 2014 3:13 AM, "Jesse Gumm" notifications@github.com wrote:
> 
> > Pmods were indeed removed in R16B, and ChicagoBoss uses a parse
> > transform
> > provided by the OTP team (https://github.com/erlang/pmod_transform) to
> > support pmods.
> > 
> > I don't know what the fix would be to get vimerl to support them,
> > though.
> > I've just dealt with it when necessary.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jimenezrick/vimerl/issues/65#issuecomment-44487316>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jimenezrick/vimerl/issues/65#issuecomment-44500549.

## 

Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
