### ISSUE TITLE
New deps enumeraiton logic breaks `include_lib` for files from deps directory.

### ISSUE THREAD

**Issue by sumerman** [jimenezrick/vimerl#75]
After commit 4178cd120ce012faec8d7c92517e0d3a0217c393 vim highlights all `include_lib` directives in red when I edit files that are located inside deps directory.

**Comment by jimenezrick** [comment]
Without this commit, do you suffer any other issue?

**Comment by sumerman** [comment]
No, without it `vimerl` works as expected. I'm on 823bf8c right now.

**Comment by jimenezrick** [comment]
4178cd1 reverted.

**Comment by sumerman** [comment]
Thanks, works as expected.
