### ISSUE TITLE
Differences between this and vim-erlang

### ISSUE THREAD

**Issue by rgrinberg** [jimenezrick/vimerl#79]
I see a massive family of erlang plugins for vim at https://github.com/vim-erlang

Most of them seem to be unmaintained forks of people's repos. But some, notably, the runtime files, omnicomplete, and the compiler seem to be maintained. Are you aware of any differences those plugins have compared to vimerl?

**Comment by jimenezrick** [comment]
Not really. I just started hacking on vimerl as I found it to be the most feature complete and then it started diverging from the original repository which is completely unmaintained.

**Comment by rgrinberg** [comment]
It's true that the original fork is unmaintained but perhaps the family of plugins I linked deserve a second look. Either way, I will use vimerl for now simply because it works well for me and it's less plugins to maintain.
