### ISSUE TITLE
cygwin compatibility

### ISSUE THREAD

**Issue by reyven** [jimenezrick/vimerl#9]
when using the plugin in a cygwin environment i came across two major issues:

escript expects windows-style paths (backslashes instead of slashes etc.), so erlang_check_file, erlang_complete_file, etc. should be set accordingly.

the erlang shell on windows does not support the "-man" command, so when code completion calls it, vim crashes.

**Comment by jimenezrick** [comment]
I could expose the variables that define the paths for `erlang_check.erl` and `erlang_complete.erl`. So you can set to something that works for you.

About the `erl -man` command, did you try to modify the variable `g:erlang_keywordprg`?
It is initially set to:

```
let g:erlang_keywordprg = 'erl -man'
```

If I recall correctly, `erl -man` is just used to show the man page of  a module using the `K` command, not for code completion.

**Comment by jimenezrick** [comment]
Well, if the issues persist, please reopen the bug. So, I close now this issue if there is no further info.
